version: '3'
services:
  nifi:
    image: apache/nifi:1.19.0
    container_name: nifi
    ports:
      - "8443:8443"
    environment:
      SINGLE_USER_CREDENTIALS_USERNAME: admin
      SINGLE_USER_CREDENTIALS_PASSWORD: adminadminadminadmin
      NIFI_WEB_HTTPS_PORT: 8443
      NIFI_WEB_HTTP_HOST: 0.0.0.0
      NIFI_REMOTE_INPUT_HOST: 0.0.0.0
      NIFI_CLUSTER_IS_NODE: 'false'
      NIFI_CLUSTER_NODE_PROTOCOL_PORT: 8082
      NIFI_ZK_CONNECT_STRING: 0.0.0.0:2181
      NIFI_ELECTION_MAX_WAIT: 1 min
      NIFI_SENSITIVE_PROPS_KEY: 'sensitive_props_key'
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: nifi
      POSTGRES_PASSWORD: nifi
      POSTGRES_DB: nifi
    ports:
      - "5432:5432"

