version: '3'
services:
  nifi:
    image: apache/nifi:1.19.0
    container_name: nifi
    ports:
      - "8443:8443"
    environment:
      SINGLE_USER_CREDENTIALS_USERNAME: admin
      SINGLE_USER_CREDENTIALS_PASSWORD: ctsBtRBKHRAx69EqUghvvgEvjnaLjFEB
      NIFI_WEB_HTTPS_PORT: 8443
      NIFI_WEB_HTTP_HOST: 0.0.0.0
      NIFI_REMOTE_INPUT_HOST: 0.0.0.0
      NIFI_CLUSTER_IS_NODE: 'false'
      NIFI_CLUSTER_NODE_PROTOCOL_PORT: 8082
      NIFI_ZK_CONNECT_STRING: 0.0.0.0:2181
      NIFI_ELECTION_MAX_WAIT: 1 min
      NIFI_SENSITIVE_PROPS_KEY: 'sensitive_props_key'
    volumes:
      - nifi_conf:/opt/nifi/nifi-current/conf
      - nifi_content_repository:/opt/nifi/nifi-current/content_repository
      - nifi_database_repository:/opt/nifi/nifi-current/database_repository
      - nifi_flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - nifi_provenance_repository:/opt/nifi/nifi-current/provenance_repository
      - nifi_state:/opt/nifi/nifi-current/state
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:8443/nifi/"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  nifi_conf:
  nifi_content_repository:
  nifi_database_repository:
  nifi_flowfile_repository:
  nifi_provenance_repository:
  nifi_state: